name: Docker Image CI

on:
  push:
    branches: [ "next-auth-fix" ]

jobs:
  release-image-on-midas:
    name: Release on Midas
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/formbricks?schema=public"
    steps:
      - name: Generate Random NEXTAUTH_SECRET
        run: |
          SECRET=$(openssl rand -hex 32)
          echo "NEXTAUTH_SECRET=$SECRET" >> $GITHUB_ENV

      - name: Generate Random ENCRYPTION_KEY
        run: |
          SECRET=$(openssl rand -hex 32)
          echo "ENCRYPTION_KEY=$SECRET" >> $GITHUB_ENV

      - name: Checkout Repo
        uses: actions/checkout@v2
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/midas-formbricks:latest
          build-args: |
            NEXTAUTH_SECRET=${{ env.NEXTAUTH_SECRET }}
            DATABASE_URL=${{ env.DATABASE_URL }}
            ENCRYPTION_KEY=${{ env.ENCRYPTION_KEY }}